/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SseIndexRouteImport } from './routes/sse/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as ImagesImageIdIndexRouteImport } from './routes/images/$imageId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SseIndexRoute = SseIndexRouteImport.update({
  id: '/sse/',
  path: '/sse/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesImageIdIndexRoute = ImagesImageIdIndexRouteImport.update({
  id: '/images/$imageId/',
  path: '/images/$imageId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/images': typeof ImagesIndexRoute
  '/sse': typeof SseIndexRoute
  '/images/$imageId': typeof ImagesImageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/images': typeof ImagesIndexRoute
  '/sse': typeof SseIndexRoute
  '/images/$imageId': typeof ImagesImageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/images/': typeof ImagesIndexRoute
  '/sse/': typeof SseIndexRoute
  '/images/$imageId/': typeof ImagesImageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/images' | '/sse' | '/images/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/images' | '/sse' | '/images/$imageId'
  id: '__root__' | '/' | '/images/' | '/sse/' | '/images/$imageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  SseIndexRoute: typeof SseIndexRoute
  ImagesImageIdIndexRoute: typeof ImagesImageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sse/': {
      id: '/sse/'
      path: '/sse'
      fullPath: '/sse'
      preLoaderRoute: typeof SseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$imageId/': {
      id: '/images/$imageId/'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  SseIndexRoute: SseIndexRoute,
  ImagesImageIdIndexRoute: ImagesImageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
